### PR TITLE
fix benchmarks, paraID and genesis

### LINKED ISSUE #995: Resolve manta RT benchmarking issue
https://discord.com/channels/794744506536034324/856737997411188736/1065347978786766908

Followup to #994

### PR DESCRIPTION
**Pull request by Garandor**
fixes https://github.com/Manta-Network/Manta/issues/995 https://github.com/Manta-Network/Manta/issues/957 https://github.com/Manta-Network/Manta/issues/667

- [x] ParaID
- [x] Regenerate
- [x] Fix benchmark issue #995 
- [x] ~~Regenerate weights~~ Used calamari weights due to runner failure
- [x] Regenerate genesis

Signed-off-by: Adam Reif <Garandor@manta.network>

---

Before we can approve this PR for merge, please make sure that **all** the following items have been checked off:
- [x] Connected to an issue with discussion and accepted design using zenhub "Connect issue" button below
- [x] Added **one** label out of the `L-` group to this PR
- [x] Added **one or more** labels from the `A-` and `C-` groups to this PR
- [x] Explicitly labelled `A-calamari`, `A-dolphin` and/or `A-manta` if your changes are meant for/impact either of these (CI depends on it)
- [x] Re-reviewed `Files changed` in the Github PR explorer.

Situational Notes:
- If adding functionality, write unit tests!
- If importing a new pallet, choose a proper module index for it, and allow it in `BaseFilter`. Ensure **every** extrinsic works from front-end. If there's corresponding tool, ensure both work for each other.
- If needed, update our Javascript/Typescript APIs. These APIs are officially used by exchanges or community developers.
- If modifying existing runtime storage items, make sure to implement storage migrations for the runtime and test them with `try-runtime`. This includes migrations inherited from upstream changes, and you can search the diffs for modifications of `#[pallet::storage]` items to check for any.

### CODE REVIEW

File: node/src/chain_specs/manta/mainnet_genesis.rs [hunk 1]
```diff
@@ -0,0 +1,194 @@
...
+    nodeid: MultiaddrWithPeerId,
+    keys: SessionKeys,
+}
+impl Collator {
+    fn new(acc: AccountId, nodeid: MultiaddrWithPeerId, keys: SessionKeys) -> Collator {
+        Self { acc, nodeid, keys }
+    }
+}
+
+fn manta_mainnet_genesis(genesis_collators: Vec<Collator>) -> GenesisConfig {
```
Comment (Garandor) [inline node/src/chain_specs/manta/mainnet_genesis.rs:36]: Looking for opinions @ghzlatarev @Dengjianping  on whether you guys think preserving this code is worth the subfolder structure.
We can split the module further to separate the various testnets as we go along to keep things tidy.

This is not compiled unless it's declared as a module in mod.rs, so if this goes out of date it won't break us

Comment (ghzlatarev) [reply node/src/chain_specs/manta/mainnet_genesis.rs:36]: Why not put this in the manta.rs file, not sure I understand,

Comment (Garandor) [reply node/src/chain_specs/manta/mainnet_genesis.rs:36]: 1. This is dead code that's unused after creating the genesis once
2. This is long and obscures the active code in there

See this comment https://github.com/Manta-Network/Manta/pull/968/files#diff-0e3b506506fc2fca53c0fe4cd8842c4fdde16f2a0503840c38f424eedb31ca21R222

Comment (ghzlatarev) [reply node/src/chain_specs/manta/mainnet_genesis.rs:36]: Oh I see now, I thought the whole manta.rs file was deleted. 
This seems ok to me. If someone needs to make a new chain-spec, they won't have to find this old PR and copy the file :D

File: node/src/chain_specs/manta/mainnet_genesis.rs [hunk 2]
```diff
@@ -0,0 +1,194 @@
...
+            SessionKeys::new((
+                hex!("1eda33797b226fed66ea3ac327a77f26b594b90bc9e9af7416a651bef07a7c72").unchecked_into(), // ss58: dfXFU5LYyQj5vzHeaHbVfhyenuibJJPGSpPonKCPNw6qsUwSm
+                hex!("bec2a422e8b72b6f5423eb2ec59d9727e580227e0e0327247d516593ec7b5312").unchecked_into(), // ss58: dfas8jnCTfPXtVvwAu15PtX6WAc3rw4iacCHeuj7qniepWtJE
+            ))
+        ),
+    ];
+    let genesis_collators_clone = genesis_collators.clone(); // so we can move it into the constructor closure
+
+    MantaChainSpec::from_genesis(
+        "Shark Parachain",
```
Comment (Dengjianping) [inline node/src/chain_specs/manta/mainnet_genesis.rs]: Not sure why it's `Shark Parachain`.

File: node/src/chain_specs/manta/mainnet_genesis.rs [hunk 3]
```diff
@@ -0,0 +1,194 @@
...
+            hex!("7a5cef43508640b6839c37a41272dec83dda4df28503bd87436c197d213f692c").into(),
+            INITIAL_COLLATOR_BALANCE,
+        ), // COLLATOR 4
+        (
+            hex!("4039a894994d326e32801a0fc19a267383b6231e74bc9c3fd1021d949d849406").into(),
+            INITIAL_COLLATOR_BALANCE,
+        ), // COLLATOR 5
+        (
+            root_key.clone(),
+            TOTAL_ISSUANCE - 4 * INITIAL_CONTROLLER_BALANCE - 4 * INITIAL_COLLATOR_BALANCE,
```
Comment (Dengjianping) [inline node/src/chain_specs/manta/mainnet_genesis.rs:77]: Are we going to assign all rest of tokens to root?

File: node/src/chain_specs/manta/mainnet_genesis.rs (hunk 1 above)
Comment (Dengjianping) [reply node/src/chain_specs/manta/mainnet_genesis.rs:36]: I'm ok with a new folder for manta chain spec.

File: node/src/chain_specs/manta/mainnet_genesis.rs [hunk 4]
```diff
@@ -0,0 +1,194 @@
...
+            INITIAL_CONTROLLER_BALANCE,
+        ), // CONTROLLER 2 ss58 14j2dssnCyQD2xWezTvZmbZPSKDBrwKcAcBtXrE6XgeGfzGx
+        (
+            hex!("3e31eaf98e0f6dd9b088c095757fac00dc9e3fe6af29e42caea94f7d76dd3444").into(),
+            INITIAL_CONTROLLER_BALANCE,
+        ), // CONTROLLER 3 ss58 12QYoFyrrEomSq4tMPxVxnWvPwVVKQHUpDWZuDxcg5Gv3c9E
+        (
+            hex!("0619e4018531059b677d70b476b72431d3e88fe71d2c27bba5d945975e824956").into(),
+            INITIAL_CONTROLLER_BALANCE,
+        ), // COLLATOR 1
```
Comment (ghzlatarev) [inline node/src/chain_specs/manta/mainnet_genesis.rs:58]: these are the mutlisig signatories right ?

File: node/src/chain_specs/manta/mainnet_genesis.rs (hunk 3 above)
Comment (ghzlatarev) [inline node/src/chain_specs/manta/mainnet_genesis.rs:77]: Shouldn't it be `4 * INITIAL_CONTROLLER_BALANCE - 5 * INITIAL_COLLATOR_BALANCE`

File: node/src/chain_specs/manta/mainnet_genesis.rs (hunk 2 above)
Comment (Garandor) [reply node/src/chain_specs/manta/mainnet_genesis.rs]: Because a Shark is the same family of animal as a manta, but not a manta :)
zqh asked the same thing, check discord

File: node/src/chain_specs/manta/mainnet_genesis.rs (hunk 3 above)
Comment (Garandor) [reply node/src/chain_specs/manta/mainnet_genesis.rs:77]: yes

File: node/src/chain_specs/manta/mainnet_genesis.rs (hunk 4 above)
Comment (Garandor) [reply node/src/chain_specs/manta/mainnet_genesis.rs:58]: Everyone marked as CONTROLLER is, yes

File: node/src/chain_specs/manta/mainnet_genesis.rs (hunk 3 above)
Comment (Garandor) [reply node/src/chain_specs/manta/mainnet_genesis.rs:77]: one collator has a higher balance for emergency resolution, so its 4 and 4 instead of 3 and 5

File: node/src/chain_specs/manta/mainnet_genesis.rs [hunk 5]
```diff
@@ -0,0 +1,194 @@
+use super::*;
```
Comment (Dengjianping) [inline node/src/chain_specs/manta/mainnet_genesis.rs:19]: Can you add a header here?

Comment (Garandor) [reply node/src/chain_specs/manta/mainnet_genesis.rs:19]: Thanks, totally forgot

File: node/src/chain_specs/manta/mainnet_genesis.rs (hunk 3 above)
Comment (ghzlatarev) [reply node/src/chain_specs/manta/mainnet_genesis.rs:77]: ok

**Review by ghzlatarev — DISMISSED** [review]

File: node/src/chain_specs/manta/mainnet_genesis.rs [hunk 6]
```diff
@@ -0,0 +1,212 @@
...
+                .collect(),
+            delegations: vec![],
+            // set to 0 inflation at genesis
+            inflation_config: manta_runtime::staking::inflation_config::<manta_runtime::Runtime>(),
+        },
+        parachain_info: manta_runtime::ParachainInfoConfig {
+            parachain_id: MANTA_PARACHAIN_ID.into(),
+        },
+        collator_selection: manta_runtime::CollatorSelectionConfig {
+            invulnerables: vec![],
```
Comment (ferrell-code) [inline node/src/chain_specs/manta/mainnet_genesis.rs:113]: Reason to not make `genesis_collators` invulnerables

Comment (Garandor) [reply node/src/chain_specs/manta/mainnet_genesis.rs:113]: collators are managed by `parachain_staking`

Comment (ferrell-code) [reply node/src/chain_specs/manta/mainnet_genesis.rs:113]: Ah yeah, I looked at diff between calamari genesis.

Invulnerables are unneeded because we will have staking enabled from the get-go on Manta

**Review by ferrell-code — COMMENTED** [review]
Good on my end, we just need to register ParaId

File: node/src/chain_specs/manta/mod.rs [hunk 7]
```diff
@@ -0,0 +1,227 @@
...
+    )?;
+    spec.extensions_mut().para_id = MANTA_PARACHAIN_ID;
+    Ok(spec)
+}
+
+/// Returns the Manta mainnet chainspec, generated to the below json file using
+/// using Ok(mainnet_genesis::manta_mainnet_config())
+/// cargo run -- build-spec --chain manta --raw
+pub fn manta_config() -> Result<MantaChainSpec, String> {
+    MantaChainSpec::from_json_bytes(&include_bytes!("../../../../genesis/manta-genesis.json")[..])
```
Comment (Garandor) [inline node/src/chain_specs/manta/mod.rs:226]: one question here, why are we not using the raw json file for each of these @ghzlatarev ?
Seems that would be more resilient against client type changes.
```suggestion
    MantaChainSpec::from_json_bytes(&include_bytes!("../../../../genesis/manta-genesis-raw.json")[..])
```

**Review by ferrell-code — DISMISSED** [review]

File: node/src/chain_specs/manta/mod.rs (hunk 7 above)
Comment (Garandor) [reply node/src/chain_specs/manta/mod.rs:226]: nvm, answering myself: if the input is a raw json, one can't do `manta build-spec --chain=manta`, the output will be identical to `manta build-spec --chain=manta --raw`

**Review by ferrell-code — APPROVED** [review]
Open issue when merged to update the manta benchmarks once we can run them

**Comment by Garandor** [comment]
> Open issue when merged to update the manta benchmarks once we can run them

Not needed, we'll rebenchmark with the next RT upgrade/on next release

**Review by ghzlatarev — APPROVED** [review]
