### PR TITLE
Fix AssetManager's update_asset_metadata

### LINKED ISSUE #462: Fix AssetManager's update_asset_metadata
* `AssetManager`'s `update_asset_metadata` is only updating an internal structure which is not being used anywhere
* Fix this as it should also update the underlying Assets data
* Add a test to check metadata items are actually updated

### PR DESCRIPTION
**Pull request by ghzlatarev**
Signed-off-by: ghzlatarev <ghzlatarev@gmail.com>

## Description

closes: #462

* `AssetManager`'s `update_asset_metadata` was not actually updating the underlying `Assets` data, so now the extrinsic is calling the `T::AssetRegistrar::update_asset_metadata` in order to do so.
* Added a test case to make sure that metadata items, like symbol, name, decimals are being updated.
* `NextAssetId` storage should be set to `StartNonNativeAssetId` instead of `NativeAssetId` on genesis. Fix benchmarking, add asset-manager to benchmarking workflow.

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [x] Wrote unit tests.
- [x] Updated relevant documentation in the code.
- [x] Added **one** line describing your change in `<branch>/CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer.
- [x] If runtime changes, need to update the version numbers properly:
   * `authoring_version`: The version of the authorship interface. An authoring node will not attempt to author blocks unless this is equal to its native runtime.
   * `spec_version`: The version of the runtime specification. A full node will not attempt to use its native runtime in substitute for the on-chain Wasm runtime unless all of spec_name, spec_version, and authoring_version are the same between Wasm and native.
   * `impl_version`: The version of the implementation of the specification. Nodes are free to ignore this; it serves only as an indication that the code is different; as long as the other two versions are the same then while the actual code may be different, it is nonetheless required to do the same thing. Non-consensus-breaking optimizations are about the only changes that could be made which would result in only the impl_version changing.
   * `transaction_version`: The version of the extrinsics interface. This number must be updated in the following circumstances: extrinsic parameters (number, order, or types) have been changed; extrinsics or pallets have been removed; or the pallet order in the construct_runtime! macro or extrinsic order in a pallet has been changed. If this number is updated, then the spec_version must also be updated 
- [x] Verify benchmarks & weights have been updated for any modified runtime logics
- [x] If import a new pallet, choose a proper module index for it, and allow it in `BaseFilter`. Ensure **every** extrinsic works from front-end. If there's corresponding tool, ensure both work for each other.
- [x] If needed, update our Javascript/Typescript APIs. These APIs are offcially used by exchanges or community developers.
- [x] If modifying existing runtime storage items, make sure to implement storage migrations for the runtime and test them with `try-runtime`. This includes migrations inhreited from upstream changes, and you can search the diffs for modifications of `#[pallet::storage]` items to check for any.

### CODE REVIEW

**Review by Dengjianping — APPROVED** [review]
LGTM!

**Comment by stechu** [comment]
If you look at `AssetRegistrarMetadata`'s implementation, like:

https://github.com/Manta-Network/Manta/blob/manta/runtime/primitives/src/assets.rs#L30 
```rust
/// The metadata of a Manta Asset
#[derive(Clone, Default, Eq, Debug, PartialEq, Ord, PartialOrd, Encode, Decode, TypeInfo)]
pub struct AssetRegistarMetadata<Balance> {
	pub name: Vec<u8>,
	pub symbol: Vec<u8>,
	pub decimals: u8,
	pub evm_address: Option<H160>,
	pub is_frozen: bool,
	pub min_balance: Balance,
	/// `is_sufficient`: Whether a non-zero balance of this asset is deposit of sufficient
	/// value to account for the state bloat associated with its balance storage. If set to
	/// `true`, then non-zero balances may be stored without a `consumer` reference (and thus
	/// an ED in the Balances pallet or whatever else is used to control user-account state
	/// growth).
	/// For example, if is_sufficient set to `false`, a fresh account cannot receive XCM tokens.
	pub is_sufficient: bool,
}
```
This is more than what `Pallet-Asset` can store. That's why `AssetIdMetadata` is needed as a storage item.

File: pallets/asset-manager/src/lib.rs [hunk 1]
```diff
@@ -320,7 +313,9 @@ pub mod pallet {
 				AssetIdLocation::<T>::contains_key(&asset_id),
 				Error::<T>::UpdateNonExistAsset
 			);
-			AssetIdMetadata::<T>::insert(&asset_id, &metadata);
+
+			T::AssetRegistrar::update_asset_metadata(asset_id, metadata.clone().into())?;
```
Comment (stechu) [inline pallets/asset-manager/src/lib.rs]: Despite we use `transactional`, it is still a good practice to put the code that could fail before the code should never fail.

**Review by stechu — CHANGES_REQUESTED** [review]

File: pallets/asset-manager/src/lib.rs [hunk 2]
```diff
@@ -256,18 +261,26 @@ pub mod pallet {
 			metadata: <T::AssetConfig as AssetConfig>::AssetRegistrarMetadata,
 		) -> DispatchResult {
 			T::ModifierOrigin::ensure_origin(origin)?;
+			ensure!(
+				!asset_id.is_one(),
```
Comment (stechu) [inline pallets/asset-manager/src/lib.rs]: The logic only works for a specific configuration.
Should check `AssetConfig<Config>::NativeAssetId` instead of `one`.

**Review by stechu — CHANGES_REQUESTED** [review]
see the detailed comments.

**Review by stechu — APPROVED** [review]
