### PR TITLE
Fix potential expect() panic in runtime code, two xcm must-fail tests, and filter out unneeded XTokens extrinsics

### LINKED ISSUE #442: Improve XCM tests
Equalize Mock environment with Dolphin:
- [x] implement same Barrier and adjust tests
- [x] use same weights configurations
- [x] equalize relay configs with Kusama/Polkadot ---> https://github.com/Manta-Network/Manta/issues/648

Write must-fail xcm tests: 
- [x] `destWeight` ->  `Barrier` 
- [x] low `amount` -> `TooExpensive`
- [x] high `amount` -> `XcmExecutionFailed`
- [x] more self_insufficient tests

More:
- [x] fuzzer tests (AFL framework) ---> https://github.com/Manta-Network/Manta/issues/647
- [x] integration tests that xcm fees go to correct account - `Treasury` ---> https://github.com/Manta-Network/Manta/issues/649

### PR DESCRIPTION
**Pull request by ghzlatarev**
## Description

closes: #442

* The `take_revenue` function of our XCM code had an `expect` call which can potentially panic. Removing the expect and handling the error now.
* Added a couple of test scenarios where it that code would previously panic.
* Filter out all `XTokens` extrinsics except `transfer()` until they are practically needed.

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [x] Wrote unit tests.
- [x] Updated relevant documentation in the code.
- [x] Added **one** line describing your change in `<branch>/CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer.
- [x] If runtime changes, need to update the version numbers properly:
   * `authoring_version`: The version of the authorship interface. An authoring node will not attempt to author blocks unless this is equal to its native runtime.
   * `spec_version`: The version of the runtime specification. A full node will not attempt to use its native runtime in substitute for the on-chain Wasm runtime unless all of spec_name, spec_version, and authoring_version are the same between Wasm and native.
   * `impl_version`: The version of the implementation of the specification. Nodes are free to ignore this; it serves only as an indication that the code is different; as long as the other two versions are the same then while the actual code may be different, it is nonetheless required to do the same thing. Non-consensus-breaking optimizations are about the only changes that could be made which would result in only the impl_version changing.
   * `transaction_version`: The version of the extrinsics interface. This number must be updated in the following circumstances: extrinsic parameters (number, order, or types) have been changed; extrinsics or pallets have been removed; or the pallet order in the construct_runtime! macro or extrinsic order in a pallet has been changed. If this number is updated, then the spec_version must also be updated 
- [x] Verify benchmarks & weights have been updated for any modified runtime logics
- [x] If import a new pallet, choose a proper module index for it, and allow it in `BaseFilter`. Ensure **every** extrinsic works from front-end. If there's corresponding tool, ensure both work for each other.
- [x] If needed, update our Javascript/Typescript APIs. These APIs are offcially used by exchanges or community developers.
- [x] If modifying existing runtime storage items, make sure to implement storage migrations for the runtime and test them with `try-runtime`. This includes migrations inhreited from upstream changes, and you can search the diffs for modifications of `#[pallet::storage]` items to check for any.

### CODE REVIEW

File: runtime/primitives/src/xcm.rs [hunk 1]
```diff
@@ -278,7 +278,8 @@ impl<
 			Ok((asset_id, amount)) => {
 				if !amount.is_zero() {
 					Assets::mint_into(asset_id, &ReceiverAccount::get(), amount)
-						.expect("`mint_into` cannot generally fail; qed");
+						.map_err(|err| log::debug!("mint_into failed with {:?}", err))
```
Comment (Dengjianping) [inline runtime/primitives/src/xcm.rs]: Good catch.
Just a suggestion, you can add a filter flag here, like
```rust
log::debug!(target: "manta-xcm", "mint_into failed with {:?}", err)
```

So now, we can filter manta xcm by this param `-lmanta-xcm=debug`

Comment (ghzlatarev) [reply runtime/primitives/src/xcm.rs]: Aaa that's what this `target` is for. Yeah will do.

**Review by Dengjianping — APPROVED** [review]
LGTM!

**Review by stechu — APPROVED** [review]
