### PR TITLE
Equalize Barrier impl between Calamari/Dolphin and mock parachain for XCM tests

### LINKED ISSUE #442: Improve XCM tests
Equalize Mock environment with Dolphin:
- [x] implement same Barrier and adjust tests
- [x] use same weights configurations
- [x] equalize relay configs with Kusama/Polkadot ---> https://github.com/Manta-Network/Manta/issues/648

Write must-fail xcm tests: 
- [x] `destWeight` ->  `Barrier` 
- [x] low `amount` -> `TooExpensive`
- [x] high `amount` -> `XcmExecutionFailed`
- [x] more self_insufficient tests

More:
- [x] fuzzer tests (AFL framework) ---> https://github.com/Manta-Network/Manta/issues/647
- [x] integration tests that xcm fees go to correct account - `Treasury` ---> https://github.com/Manta-Network/Manta/issues/649

### PR DESCRIPTION
**Pull request by ghzlatarev**
## Description

closes: #442 

* Equalize xcm `Barrier` configurations between production and test environment, to get the test cases closer to reality.
* Remove unnecessary Barrier which was supposed to be letting through messages from the relay's executive plurality. Even though the message is let through we don't have a convereter for `Plurality { id: BodyId::Executive, .. }` multilocation, so it's not going to be interpreted.
* Adjust tests to account for Barriers

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [x] Wrote unit tests.
- [x] Updated relevant documentation in the code.
- [x] Added **one** line describing your change in `<branch>/CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer.
- [x] If runtime changes, need to update the version numbers properly:
   * `authoring_version`: The version of the authorship interface. An authoring node will not attempt to author blocks unless this is equal to its native runtime.
   * `spec_version`: The version of the runtime specification. A full node will not attempt to use its native runtime in substitute for the on-chain Wasm runtime unless all of spec_name, spec_version, and authoring_version are the same between Wasm and native.
   * `impl_version`: The version of the implementation of the specification. Nodes are free to ignore this; it serves only as an indication that the code is different; as long as the other two versions are the same then while the actual code may be different, it is nonetheless required to do the same thing. Non-consensus-breaking optimizations are about the only changes that could be made which would result in only the impl_version changing.
   * `transaction_version`: The version of the extrinsics interface. This number must be updated in the following circumstances: extrinsic parameters (number, order, or types) have been changed; extrinsics or pallets have been removed; or the pallet order in the construct_runtime! macro or extrinsic order in a pallet has been changed. You can run the `metadata_diff.yml` workflow for help. If this number is updated, then the `spec_version` must also be updated 
- [x] Verify benchmarks & weights have been updated for any modified runtime logics
- [x] If importing a new pallet, choose a proper module index for it, and allow it in `BaseFilter`. Ensure **every** extrinsic works from front-end. If there's corresponding tool, ensure both work for each other.
- [x] If needed, update our Javascript/Typescript APIs. These APIs are officially used by exchanges or community developers.
- [x] If modifying existing runtime storage items, make sure to implement storage migrations for the runtime and test them with `try-runtime`. This includes migrations inherited from upstream changes, and you can search the diffs for modifications of `#[pallet::storage]` items to check for any.

### CODE REVIEW

File: runtime/common/tests/xcm_mock/parachain.rs [hunk 1]
```diff
@@ -209,8 +210,35 @@ pub type MultiAssetTransactor = MultiAssetAdapter<
...
+        MultiLocation { parents: 1, interior: Here }
+    };
+}
+match_type! {
+    pub type ParentOrSiblings: impl Contains<MultiLocation> = {
+        MultiLocation { parents: 1, interior: Here } |
+        MultiLocation { parents: 1, interior: X1(_) }
+    };
+}
+pub type Barrier = (
```
Comment (Garandor) [inline runtime/common/tests/xcm_mock/parachain.rs:226]: could you type alias to a runtime's barrier instead of recreating the type here?
If the code is meant to be identical, there's no need to duplicate it, right?

**Review by Garandor — DISMISSED** [review]
LGTM

File: runtime/common/tests/xcm_mock/parachain.rs (hunk 1 above)
Comment (ghzlatarev) [reply runtime/common/tests/xcm_mock/parachain.rs:226]: Yeah we could directly import and use either the Dolphin or Calamari barrier. 
I'm going to log this and think about this a bit more, because we could import a lot of other configurations as well, or just move things into the Dolphin or Calamari folders. But not the ones which are generic over the Runtime, so it will get really mixed.

**Review by Garandor — DISMISSED** [review]

File: runtime/common/tests/xcm_mock/parachain.rs [hunk 2]
```diff
@@ -18,7 +18,7 @@
 
 use codec::{Decode, Encode};
 use frame_support::{
-    assert_ok, construct_runtime,
+    assert_ok, construct_runtime, match_type,
```
Comment (Dengjianping) [inline runtime/common/tests/xcm_mock/parachain.rs]: This macro is going to be deprecated, please `match_types`.

Comment (ghzlatarev) [reply runtime/common/tests/xcm_mock/parachain.rs]: This branch is still on 0.9.18

File: runtime/common/tests/xcm_mock/parachain.rs [hunk 3]
```diff
@@ -209,8 +210,35 @@ pub type MultiAssetTransactor = MultiAssetAdapter<
...
+    };
+}
+pub type Barrier = (
+    // Allows local origin messages which call weight_credit >= weight_limit.
+    TakeWeightCredit,
+    // Allows non-local origin messages, for example from from the xcmp queue,
+    // which have the ability to deposit assets and pay for their own execution.
+    AllowTopLevelPaidExecutionFrom<Everything>,
+    // Parent root gets free execution
+    AllowUnpaidExecutionFrom<ParentLocation>,
```
Comment (Dengjianping) [inline runtime/common/tests/xcm_mock/parachain.rs:233]: Does this line mean relaychain can send xcm to us without paid?

File: runtime/common/tests/xcm_tests.rs [hunk 4]
```diff
@@ -39,12 +39,51 @@ use crate::xcm_mock::parachain::{
...
+            weight_limit: Limited(3999999999),
+        },
+        DepositAsset {
+            assets: Wild(All),
+            max_assets: 1,
+            beneficiary: MultiLocation {
+                parents: 0,
+                interior: X1(AccountId32 {
+                    network: Any,
+                    id: [
```
Comment (Dengjianping) [inline runtime/common/tests/xcm_tests.rs:75]: Who is it?

File: runtime/common/tests/xcm_tests.rs [hunk 5]
```diff
@@ -132,9 +200,11 @@ fn xcmp() {
         ));
     });
 
+    // The `AllowUnpaidExecutionFrom<ParentLocation>` barrier implementation
```
Comment (Dengjianping) [inline runtime/common/tests/xcm_tests.rs:203]: So now, we only execute the xcm which contains `Transact` from relaychain?

File: runtime/common/tests/xcm_mock/parachain.rs (hunk 3 above)
Comment (ghzlatarev) [reply runtime/common/tests/xcm_mock/parachain.rs:233]: Yes, this has been the case so far. This basically means from the root because only the root can send messages without `ClearOrigin`

File: runtime/common/tests/xcm_tests.rs (hunk 4 above)
Comment (ghzlatarev) [reply runtime/common/tests/xcm_tests.rs:75]: Just a random account, it doesn't matter.

File: runtime/common/tests/xcm_tests.rs (hunk 5 above)
Comment (ghzlatarev) [reply runtime/common/tests/xcm_tests.rs:203]: No, this is just one of the barriers.

**Review by Dengjianping — DISMISSED** [review]
LGTM!

**Review by Dengjianping — APPROVED** [review]
lgtm!

**Review by Garandor — APPROVED** [review]
